/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ShowsIndexRouteImport } from './routes/shows.index'
import { Route as ShowsShowIdRouteImport } from './routes/shows.$showId'
import { Route as ApiIptvFetchRouteImport } from './routes/api/iptv/fetch'
import { Route as ApiIptvImageRouteImport } from './routes/api/iptv/image'
import { Route as ApiIptvStreamRouteImport } from './routes/api/iptv/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowsRoute,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/$showId',
  path: '/$showId',
  getParentRoute: () => ShowsRoute,
} as any)
const ApiIptvFetchRoute = ApiIptvFetchRouteImport.update({
  id: '/api/iptv/fetch',
  path: '/api/iptv/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvImageRoute = ApiIptvImageRouteImport.update({
  id: '/api/iptv/image',
  path: '/api/iptv/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvStreamRoute = ApiIptvStreamRouteImport.update({
  id: '/api/iptv/stream',
  path: '/api/iptv/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRouteWithChildren
  '/watch': typeof WatchRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/shows/': typeof ShowsIndexRoute
  '/api/iptv/fetch': typeof ApiIptvFetchRoute
  '/api/iptv/image': typeof ApiIptvImageRoute
  '/api/iptv/stream': typeof ApiIptvStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/movies': typeof MoviesRoute
  '/watch': typeof WatchRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/shows': typeof ShowsIndexRoute
  '/api/iptv/fetch': typeof ApiIptvFetchRoute
  '/api/iptv/image': typeof ApiIptvImageRoute
  '/api/iptv/stream': typeof ApiIptvStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/movies': typeof MoviesRoute
  '/shows': typeof ShowsRouteWithChildren
  '/watch': typeof WatchRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/shows/': typeof ShowsIndexRoute
  '/api/iptv/fetch': typeof ApiIptvFetchRoute
  '/api/iptv/image': typeof ApiIptvImageRoute
  '/api/iptv/stream': typeof ApiIptvStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live'
    | '/movies'
    | '/shows'
    | '/watch'
    | '/shows/$showId'
    | '/shows/'
    | '/api/iptv/fetch'
    | '/api/iptv/image'
    | '/api/iptv/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/movies'
    | '/watch'
    | '/shows/$showId'
    | '/shows'
    | '/api/iptv/fetch'
    | '/api/iptv/image'
    | '/api/iptv/stream'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/movies'
    | '/shows'
    | '/watch'
    | '/shows/$showId'
    | '/shows/'
    | '/api/iptv/fetch'
    | '/api/iptv/image'
    | '/api/iptv/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  MoviesRoute: typeof MoviesRoute
  ShowsRoute: typeof ShowsRouteWithChildren
  WatchRoute: typeof WatchRoute
  ApiIptvFetchRoute: typeof ApiIptvFetchRoute
  ApiIptvImageRoute: typeof ApiIptvImageRoute
  ApiIptvStreamRoute: typeof ApiIptvStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/'
      fullPath: '/shows/'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof ShowsRoute
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof ShowsRoute
    }
    '/api/iptv/fetch': {
      id: '/api/iptv/fetch'
      path: '/api/iptv/fetch'
      fullPath: '/api/iptv/fetch'
      preLoaderRoute: typeof ApiIptvFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv/image': {
      id: '/api/iptv/image'
      path: '/api/iptv/image'
      fullPath: '/api/iptv/image'
      preLoaderRoute: typeof ApiIptvImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv/stream': {
      id: '/api/iptv/stream'
      path: '/api/iptv/stream'
      fullPath: '/api/iptv/stream'
      preLoaderRoute: typeof ApiIptvStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShowsRouteChildren {
  ShowsShowIdRoute: typeof ShowsShowIdRoute
  ShowsIndexRoute: typeof ShowsIndexRoute
}

const ShowsRouteChildren: ShowsRouteChildren = {
  ShowsShowIdRoute: ShowsShowIdRoute,
  ShowsIndexRoute: ShowsIndexRoute,
}

const ShowsRouteWithChildren = ShowsRoute._addFileChildren(ShowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  MoviesRoute: MoviesRoute,
  ShowsRoute: ShowsRouteWithChildren,
  WatchRoute: WatchRoute,
  ApiIptvFetchRoute: ApiIptvFetchRoute,
  ApiIptvImageRoute: ApiIptvImageRoute,
  ApiIptvStreamRoute: ApiIptvStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
